update docs

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -1,6 +1,30 @@
 version: '3'
 
 tasks:
-  echo:
+  delete-all-envs:
     cmds:
-      - echo "Hello, World!"
+      - rm -rf envs/*
+    desc: すべてのTerraformファイルを削除
+    silent: true
+
+  create-vm:
+    cmds:
+      - |
+        if [ -z "{{.CLI_ARGS}}" ]; then
+          echo "Error: VM_NAME is required."
+          exit 1
+        fi
+      - cp -r template/vm envs/{{.CLI_ARGS}}
+    desc: Proxmox VMのためのTerraform Templateを作成. 例 `task create-vm -- VM_NAME`
+    silent: true
+
+  create-container:
+    cmds:
+      - |
+        if [ -z "{{.CLI_ARGS}}" ]; then
+          echo "Error: CT_NAME is required."
+          exit 1
+        fi
+      - cp -r template/container envs/{{.CLI_ARGS}}
+    desc: Proxmox ContainerのためのTerraform Templateを作成. 例 `task create-container -- CT_NAME`
+    silent: true
